In [2]:
#Download all libraries 
import pandas as pd
import numpy as np

In [11]:

# Read in the CSV file
new = pd.read_csv('/Users/nataliemac/Desktop/VCS/Python/05_Capital_Bike_Share/merged_data.csv', sep=';', low_memory=False)



new

        Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0        506.0,2020-01-01 00:00:59,2020-01-01 00:09:26,...
1        1050.0,2020-01-01 00:01:16,2020-01-01 00:18:47...
2        1687.0,2020-01-01 00:02:42,2020-01-01 00:30:50...
3        182.0,2020-01-01 00:02:44,2020-01-01 00:05:47,...
4        1002.0,2020-01-01 00:06:12,2020-01-01 00:22:54...
...                                                    ...
2216909  ,,,,,,,,,A10ED3D50E5AB612,docked_bike,2020-12-...
2216910  ,,,,,,,,,F146CC9669ABF5EC,docked_bike,2020-12-...
2216911  ,,,,,,,,,614005BC98FE93F7,docked_bike,2020-12-...
2216912  ,,,,,,,,,86783BF38F4567FA,docked_bike,2020-12-...
2216913  ,,,,,,,,,A7F61D67643CB526,classic_bike,2020-12...

[2216914 rows x 1 columns]

In [14]:
# Read in the CSV file
new = pd.read_csv('/Users/nataliemac/Desktop/VCS/Python/05_Capital_Bike_Share/merged_data.csv',low_memory=False)
new

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type,ride_id,...,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,506.0,2020-01-01 00:00:59,2020-01-01 00:09:26,31623.0,Columbus Circle / Union Station,31658.0,Rosedale Rec Center,W22189,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1050.0,2020-01-01 00:01:16,2020-01-01 00:18:47,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31606.0,Potomac & Pennsylvania Ave SE,W21067,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1687.0,2020-01-01 00:02:42,2020-01-01 00:30:50,31218.0,L'Enfant Plaza / 7th & C St SW,31271.0,Constitution Ave & 2nd St NW/DOL,W24359,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,182.0,2020-01-01 00:02:44,2020-01-01 00:05:47,31627.0,3rd & M St NE,31508.0,Gallaudet / 8th St & Florida Ave NE,W23334,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1002.0,2020-01-01 00:06:12,2020-01-01 00:22:54,31247.0,Jefferson Dr & 14th St SW,31274.0,10th & G St NW,W23441,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2216909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A10ED3D50E5AB612,...,2020-12-12 14:17:02,Jefferson Dr & 14th St SW,31247.0,19th St & Constitution Ave NW,31235.0,38.888553,-77.032427,38.892300,-77.043600,casual
2216910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F146CC9669ABF5EC,...,2020-12-03 14:06:11,Jefferson Dr & 14th St SW,31247.0,4th St & Madison Dr NW,31288.0,38.888553,-77.032427,38.890496,-77.017247,casual
2216911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,614005BC98FE93F7,...,2020-12-06 08:03:46,Jefferson Dr & 14th St SW,31247.0,19th St & Constitution Ave NW,31235.0,38.888552,-77.032427,38.892300,-77.043600,casual
2216912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86783BF38F4567FA,...,2020-12-21 14:26:59,Jefferson Dr & 14th St SW,31247.0,17th & G St NW,31277.0,38.888553,-77.032427,38.898283,-77.039732,casual
2216913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A7F61D67643CB526,...,2020-12-18 09:23:54,New Hampshire Ave & 24th St NW,31275.0,4th St & Madison Dr NW,31288.0,38.901755,-77.051084,38.890496,-77.017246,member

In [ ]:

new = pd.read_csv('/Users/nataliemac/Desktop/VCS/Python/05_Capital_Bike_Share/merged_data.csv', 
                  dtype={'ride_id': 'int', 'ended_at': 'float', 'start_station_game': 'str'})

In [32]:
print(new.columns)

Index(['Duration', 'Start date', 'End date', 'Start station number',
       'Start station', 'End station number', 'End station', 'Bike number',
       'Member type', 'ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='object')

In [33]:


new = pd.read_csv('/Users/nataliemac/Desktop/VCS/Python/05_Capital_Bike_Share/merged_data.csv')


# Convert datetime column to pandas datetime format
new['datetime'] = pd.to_datetime(new['datetime'], format='%Y-%m-%d %H:%M:%S')

/var/folders/3q/b6hzz54s5l766kwylwkwvjn00000gn/T/ipykernel_31981/3703913263.py:1: DtypeWarning: Columns (1,2,4,6,7,8,9,10,11,12,13,15,21) have mixed types. Specify dtype option on import or set low_memory=False.
  new = pd.read_csv('/Users/nataliemac/Desktop/VCS/Python/05_Capital_Bike_Share/merged_data.csv')

KeyError: 'datetime'

In [38]:

new.head(10)

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type,ride_id,...,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,506.0,2020-01-01 00:00:59,2020-01-01 00:09:26,31623.0,Columbus Circle / Union Station,31658.0,Rosedale Rec Center,W22189,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1050.0,2020-01-01 00:01:16,2020-01-01 00:18:47,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31606.0,Potomac & Pennsylvania Ave SE,W21067,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1687.0,2020-01-01 00:02:42,2020-01-01 00:30:50,31218.0,L'Enfant Plaza / 7th & C St SW,31271.0,Constitution Ave & 2nd St NW/DOL,W24359,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,182.0,2020-01-01 00:02:44,2020-01-01 00:05:47,31627.0,3rd & M St NE,31508.0,Gallaudet / 8th St & Florida Ave NE,W23334,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1002.0,2020-01-01 00:06:12,2020-01-01 00:22:54,31247.0,Jefferson Dr & 14th St SW,31274.0,10th & G St NW,W23441,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,980.0,2020-01-01 00:06:32,2020-01-01 00:22:53,31247.0,Jefferson Dr & 14th St SW,31274.0,10th & G St NW,W24013,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,974.0,2020-01-01 00:06:49,2020-01-01 00:23:03,31247.0,Jefferson Dr & 14th St SW,31274.0,10th & G St NW,W21829,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,424.0,2020-01-01 00:07:52,2020-01-01 00:14:56,31506.0,1st & Rhode Island Ave NW,31245.0,7th & R St NW / Shaw Library,78528,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,683.0,2020-01-01 00:08:10,2020-01-01 00:19:34,31628.0,1st & K St SE,31269.0,3rd St & Pennsylvania Ave SE,W24226,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,676.0,2020-01-01 00:08:20,2020-01-01 00:19:36,31293.0,31st & Water St NW,31212.0,21st & M St NW,W24315,Member,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
new.tail()

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type,ride_id,...,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
2216909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A10ED3D50E5AB612,...,2020-12-12 14:17:02,Jefferson Dr & 14th St SW,31247.0,19th St & Constitution Ave NW,31235.0,38.888553,-77.032427,38.892300,-77.043600,casual
2216910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F146CC9669ABF5EC,...,2020-12-03 14:06:11,Jefferson Dr & 14th St SW,31247.0,4th St & Madison Dr NW,31288.0,38.888553,-77.032427,38.890496,-77.017247,casual
2216911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,614005BC98FE93F7,...,2020-12-06 08:03:46,Jefferson Dr & 14th St SW,31247.0,19th St & Constitution Ave NW,31235.0,38.888552,-77.032427,38.892300,-77.043600,casual
2216912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86783BF38F4567FA,...,2020-12-21 14:26:59,Jefferson Dr & 14th St SW,31247.0,17th & G St NW,31277.0,38.888553,-77.032427,38.898283,-77.039732,casual
2216913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A7F61D67643CB526,...,2020-12-18 09:23:54,New Hampshire Ave & 24th St NW,31275.0,4th St & Madison Dr NW,31288.0,38.901755,-77.051084,38.890496,-77.017246,member

In [34]:
# count missing values for red_wine dataset
missing_values_count = new.isnull().sum()

print(missing_values_count)

total_missing = missing_values_count.sum()

print(f'Total missing values: {total_missing}')

Duration                1679514
Start date              1679514
End date                1679514
Start station number    1679514
Start station           1679514
End station number      1679514
End station             1679514
Bike number             1679514
Member type             1679514
ride_id                  537400
rideable_type            537400
started_at               537400
ended_at                 537400
start_station_name       622039
start_station_id         622039
end_station_name         634915
end_station_id           634915
start_lat                537408
start_lng                537408
end_lat                  543880
end_lng                  543880
member_casual            537400
dtype: int64
Total missing values: 22479110